#!/bin/bash
# Grep Chain
# Edwin Rietmeijer, 2020

words=$@

command=""
for word in $words
do
  command=${command}"grep ${word} "'| '
done
command=${command:0:$((${#command} - 2))}

eval $command <&0
