#!/bin/bash
# Grep Chain
# Edwin Rietmeijer, 2020

words=$@

command=""
for word in $words
do
  command=${command}"grep ${word} "'| '
done
commLen=${#command}
command=${command:0:$((commLen - 2))}

eval $command <&0
